name: CI-CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARTIFACTS_DIRECTORY: './artifacts/'
      AZURE_RESOURCEGROUP_NAME: 'rg-personregistry-development'
      AZURE_RESOURCEGROUP_LOCATION: 'australiaeast'
    steps:
      - uses: actions/checkout@v2
      
      - name: Install .NET 6
        uses: actions/setup-dotnet@v1.8.1
        with:
          dotnet-version: 6.0.x
          include-prerelease: true

      - name: Publish
        run: |
          dotnet publish 'src/PersonRegistry.WebApp/PersonRegistry.WebApp.csproj'\
            --output ${{ env.ARTIFACTS_DIRECTORY }}\
            --self-contained\
            --framework net6.0\
            --runtime linux-x64\
            --configuration release
            
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
       
      - name: Ensure Azure Resource Group Created
        uses: Azure/cli@1.0.4
        with:
          inlineScript: |
            az group create\
              --name ${{ env.AZURE_RESOURCEGROUP_NAME }}\
              --location ${{ env.AZURE_RESOURCEGROUP_LOCATION }}
              
      - name: Update Azure Resource Group
        uses: Azure/cli@1.0.4
        with:
          inlineScript: |
            az deployment group create\
              --name ${{ github.run_number }}\
              --resource-group ${{ env.AZURE_RESOURCEGROUP_NAME }}\
              --template-file 'infrastructure/azure/resource-group.bicep'\
              --parameters appServicePlanName=plan-personregistry-development\
              --parameters webAppName=app-personregistry-development\
              --parameters webApp_ASPNETCORE_ENVIRONMENT=Development
