name: CI-CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARTIFACTS_DIRECTORY: './artifacts/'
    steps:
      - uses: actions/checkout@v2
      
      - name: Install .NET 6
        uses: actions/setup-dotnet@v1.8.1
        with:
          dotnet-version: 6.0.x
          include-prerelease: true

      - name: Publish
        run: |
          dotnet publish 'src/PersonRegistry.WebApp/PersonRegistry.WebApp.csproj'\
            --output ${{ env.ARTIFACTS_DIRECTORY }}\
            --self-contained\
            --framework net6.0\
            --runtime linux-x64\
            --configuration release
            
