name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install .NET 6
        uses: actions/setup-dotnet@v1.8.1
        with:
          dotnet-version: 6.0.x
          include-prerelease: true

      - name: Build
        run: dotnet build
